creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # staging-rotate-key
          - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          # staging-argo-key
          - age1p9rynn6rcdfhx0kdks0sh5drjrjg857cuujapu04m9a2r0zarq6stdha6c
