openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.tiny

  cloudCredentialsSecretName: david-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # Temp pending move to test.harbor.stfc.ac.uk
                loadBalancerIP: "130.246.211.217"
