creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # prod-rotate-key
          - age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          # prod-argo-key
          - age1mqqfadar4vz8yfsvfd540nkhwjvxuzmf3hgr95ftp7d0dqnm7ycsfue3kv
