openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 5

  nodeGroupDefaults:
    machineFlavor: l3.micro

  cloudCredentialsSecretName: victoria-metrics-test-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # ingress ip in RJ-scratch space  project on dev
                loadBalancerIP: "130.246.211.115"
