openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  addons:
    ingress:
      enabled: false

    monitoring:
      enabled: false
