openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.small

  cloudCredentialsSecretName: staging-management-cluster-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # Temporary for testing DR scenario
                loadBalancerIP: "130.246.211.226"
