creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # staging-key
          - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          # staging-argo-key
          - age1cx49ss4m25nzm8ju80g2jmpwdj72fvyllzqj6nh3lx3jdmgqnfss80z4xs
