creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # staging-key
          - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          # staging-argo-key
          - age1z4epa5wnfx0md9yg7pv7mgf4zekyjher5sl8ev67z68nz7ykwcmqn3u0dw
