openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.nano

  clusterNetworking:
    externalNetworkId: 0dc30001-edfb-4137-be76-8e51f38fd650 # Dev External network ID

  cloudCredentialsSecretName: victoria-metrics-test-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # ingress ip in personal scratch space
                loadBalancerIP: "130.246.211.115"
