global:
  spec:
    # argocd project to use
    project: default
    source:
      # specifies source repo 
      # you'll only want to change this if you make a fork
      repoURL: https://github.com/anish-mudaraddi/cloud-deployed-apps.git
      
      # default target revision to use - if cluster values don't specify
      targetRevision: HEAD


# sets the path to the default value files for each app
# NOTE: starts at the root level of the repo

appValueFiles:
  argocd:
  - charts/apps/argocd/values.yaml

# sets the path to defualt value files for infra charts
# NOTE: starts at the root level of the repo

infraValueFiles:
  capi:
  - charts/infra/capi/values.yaml
  - charts/infra/capi/certs.yaml