global:
  clusterName: vgc59244-test
  spec:
    source:
      targetRevision: HEAD

infra:
  - name: vgc59244-test
    disableAutomated: false
    chartName: capi
    namespace: clusters
    additionalValueFiles: 
      - clusters/vgc59244-test/overrides/cluster-self-manage.yaml

apps:
  - name: argocd
    disableAutomated: false
    chartName: argocd
    namespace: argocd