global:
  hostname: "galaxy.dev.nubes.stfc.ac.uk"



oauth2-proxy:
  extraArgs:
    # limit access to stfc-cloud-dev group
    allowed-group: "stfc-cloud-dev"

galaxy:
  configs:
    galaxy.yml:
      galaxy:
        # comma spaced list of admin emails
        admin_users: "anish.mudaraddi@stfc.ac.uk"