apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  destination:
    namespace: {{ $.Values.global.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    path: charts/base/
    helm:
      valueFiles:
        - ../../clusters/{{ $.Values.global.clusterName }}/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
---