openstack-cluster:
  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # *.prod-worker.nubes.stfc.ac.uk
                loadBalancerIP: "130.246.80.243"

    monitoring:
      kubePrometheusStack:
        release:
          values:
            defaultRules:
              additionalRuleLabels:
                cluster: worker
                env: prod
            prometheus:
              ingress:
                hosts:
                  - prometheus.prod-worker.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus.prod-worker.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana.prod-worker.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana.prod-worker.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager.prod-worker.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager.prod-worker.nubes.stfc.ac.uk
                    secretName: tls-keypair
