openstack-cluster:

  cloudCredentialsSecretName: test-capi-addons-2-cloud-credentials

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.215.233"

 