apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: HEAD
    path: clusters/dev/management/argocd-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true