controlPlane:
  machineCount: 3

nodeGroups:
  - name: default-md-0
    machineCount: 2

nodeGroupDefaults:
  machineFlavor: l3.nano

addons:
  ingress:
    enabled: true
    nginx:
      release:
        values:
          controller:
            service:
              loadBalancerIP: "130.246.80.38"

  monitoring:
    enabled: true
    lokiStack:
      enabled: false
    kubePrometheusStack:
      release:
        values:
          defaultRules:
            additionalRuleLabels:
              cluster: dev-management
              env: dev
          alertmanager:
            enabled: false
            ingress:
              hosts:
                - alertmanager-mgmt.dev.nubes.stfc.ac.uk
              tls:
                - hosts:
                    - alertmanager-mgmt.dev.nubes.stfc.ac.uk
                  secretName: tls-keypair
          prometheus:
            ingress:
              hosts:
                - prometheus-mgmt.dev.nubes.stfc.ac.uk
              tls:
                - hosts:
                    - prometheus-mgmt.dev.nubes.stfc.ac.uk
                  secretName: tls-keypair
          grafana:
            ingress:
              hosts:
                - grafana-mgmt.dev.nubes.stfc.ac.uk
              tls:
                - hosts:
                    - grafana-mgmt.dev.nubes.stfc.ac.uk
                  secretName: tls-keypair
