longhorn:
  preUpgradeChecker:
    jobEnabled: false
  service:
    ui:
      type: ClusterIP

  ingress:
    enabled: "true"
    ingressClassName: nginx
    host: longhorn.example.com
    tls: false
    secureBackends: false
    path: /

  serviceMonitor:
    enabled: true


  longhornManager:
    nodeSelector: 
      longhorn.demo.io/longhorn-storage-node: "true"

  defaultSettings:
    snapshotMaxCount: 10
    snapshotDataIntegrity: true
    snapshotDataIntegtrityCronjob: true
    replicaAutoBalance: true
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
    allowVolumeCreationWithDegradedAvailability: true

  persistence:
    migratable: "true"
    