global:
  clusterName: test-capi-addons-2
  spec:
    source:
      targetRevision: main
      repoURL: https://github.com/stfc/cloud-deployed-apps.git
      namespace: argocd

infra:
  - name: test-capi-addons-2
    disableAutomated: false
    chartName: capi
    namespace: clusters
    additionalValueFiles:
      - clusters/test-capi-addons-2/overrides/infra/deployment.yaml
