victoria-metrics-cluster:
  vmselect:
    replicaCount: 5

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - name: select.vm.example.com
          path: /
          port: http
      tls:
        - secretName: vm-ingress-tls
          hosts:
            - select.vm.example.com

  vminsert:
    replicaCount: 5

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - name: insert.vm.example.com
          path: /
          port: http
      tls:
        - secretName: vm-ingress-tls
          hosts:
            - insert.vm.example.com

  vmstorage:
    retentionPeriod: 1 # month
    replicaCount: 5

    persistentVolume:
      enabled: true
      existingClaim: ""

      size: 10Gi
      storageClass: "longhorn"
