argo-cd:
  global:
    domain: argocd.stfc.ac.uk

  server:
    # INGRESS - disable this if you're having problems and enable loadbalancer 
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls: true