openstack-cluster:
  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.nano

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.211.169"

    monitoring:
      enabled: true
      lokiStack:
        enabled: false
      kubePrometheusStack:
        release:
          values:
            defaultRules:
              additionalRuleLabels:
                cluster: dev-worker
                env: dev
            alertmanager:
              enabled: false
              ingress:
                hosts:
                  - alertmanager-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - alertmanager-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair
            prometheus:
              ingress:
                hosts:
                  - prometheus-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - prometheus-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - grafana-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair