openstack-cluster:
  kubernetesVersion: "1.28.12"
  machineImage: "capi-ubuntu-2004-kube-v1.28.12-2024-08-22"

  controlPlane:
    machineCount: 3

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    machineFlavor: l3.nano

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                loadBalancerIP: "130.246.211.106"

    monitoring:
      enabled: true
      lokiStack:
        enabled: false
      kubePrometheusStack:
        release:
          values:
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: worker
                  env: dev
              ingress:
                hosts:
                  - prometheus-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - prometheus-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana-worker.dev.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - grafana-worker.dev.nubes.stfc.ac.uk
                    secretName: tls-keypair