openstack-cluster:
  cloudCredentialsSecretName: prod-mgmt-cloud-credentials

  addons:
    monitoring:
      kubePrometheusStack:
        release:
          values:
            defaultRules:
              additionalRuleLabels:
                # these values used for alerting only - part of the email subject tag-line
                cluster: prod-worker
                env: prod
            alertmanager:
              enabled: true
              ingress:
                annotations: ""
                hosts:
                  - alertmanager-worker.prod.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - alertmanager-worker.prod.nubes.stfc.ac.uk
                    secretName: tls-keypair
            prometheus:
              ingress:
                annotations: ""
                hosts:
                  - prometheus-worker.prod.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - prometheus-worker.prod.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                annotations: ""
                hosts:
                  - grafana-worker.prod.nubes.stfc.ac.uk
                tls:
                  - hosts: 
                    - grafana-worker.prod.nubes.stfc.ac.uk
                    secretName: tls-keypair
